### PR TITLE
Set expand conditions for mailFolders,messages,events and calendarView to true.

### PR DESCRIPTION
**Pull request by andrueastman**
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1581
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1672
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1744
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1735

Mailfolders can have the `messages` property expanded.
Events/Calendarview can have the `singleValueExtendedProperties` property expanded.
Messages can have the `attachements` property expanded

### CODE REVIEW

**Comment by RHKofax** [comment]
Should MailFolders not also support $expand for ChildFolders? If not, how should you get all folders within a folder? By Default the CholdFolders property is null even when the ChildFolderCount > 0

**Comment by ashley-w-brazier-cloudm** [comment]
I can't see expand in events using 5.38

**Comment by andrueastman** [comment]
Any chance you confirm the path you are trying to call @ashley-w-brazier-cloudm? 

Looks like `$expand` exists on `/users/{user%2Did}/events` but not `groups/{group-id}/events`. This will be followed via https://github.com/microsoftgraph/msgraph-metadata/issues/553

**Comment by ashley-w-brazier-cloudm** [comment]
@andrueastman I'm using the following in Graph api explorer
/v1.0/groups/[omitted]/events/?$expand=singleValueExtendedProperties($filter=id eq 'String { [omitted]} Name [omitted]')

This works as expected
using the following example provided when you scroll to the bottom
`var result = await graphClient.Groups["{group-id}"].Events.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "singleValueExtendedProperties($filter=id eq 'String { [[omitted]} Name [omitted]')" };
});`

requestConfiguration.QueryParameters.Expand does not exist

**Comment by ashley-w-brazier-cloudm** [comment]
@andrueastman is there a workaround I can use until this is fixed? Thanks

**Comment by andrueastman** [comment]
@ashley-w-brazier-cloudm You can use the `WithUrl` function present in the request builders as below. We've authored https://github.com/microsoftgraph/msgraph-metadata/pull/554 to resolve [the issue](https://github.com/microsoftgraph/msgraph-metadata/issues/553). 

```cs
var result = await graphClient.Groups["{group-id}"].Events.WithUrl("https://graph.microsoft.com/v1.0/groups/[omitted]/events/?$expand=singleValueExtendedProperties($filter=id eq 'String { [omitted]} Name [omitted]')").GetAsync();
```

**Comment by ashley-w-brazier-cloudm** [comment]
thanks @andrueastman

**Pull request merged**
