### PR TITLE
Adds `AddAlternateKeyPaths = true`

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/305

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
Should we also do this for the other setting files as well?

**Comment by irvinesunday** [comment]
> Should we also do this for the other setting files as well?

If we enable this setting in the OpenAPI file used by GE we might not extract accurate path segments for these alternate key paths in the OpenApiUrlTreeNode which is used by Resource Explorer.
We split the path value by `/` when creating the tree node: https://github.com/microsoft/OpenAPI.NET/blob/9d82233182d11d64a12bd5c250b881e6e102f4d0/src/Microsoft.OpenApi/Services/OpenApiUrlTreeNode.cs#L158

This should be resolved in the OpenAPI.NET library first. I have created an issue to track this: https://github.com/microsoft/OpenAPI.NET/issues/1277

**Comment by baywet** [comment]
I think I agree with @andrueastman and we should at least set it for the openapi profile. Left a comment on the issue you created to understand the concern better.

**Comment by irvinesunday** [comment]
> I think I agree with @andrueastman and we should at least set it for the openapi profile. Left a comment on the issue you created to understand the concern better.

@andrueastman is suggesting we implement this change for all the profiles. My suggestion was to localise it just to **powershell** for the time being. Does Kiota also anticipate the alternate key paths in its _openapi_ document?

**Comment by baywet** [comment]
looking at [this comment](https://github.com/microsoft/OpenAPI.NET/issues/1277#issuecomment-1621806333) kiota would give you:
- directoryRoles/{id} => ...DirectoryRoles["id"] or ...DirectoryRoles.ById("id")
- directoryRoles(roleTemplateId='{roleTemplateId}') => DirectoryRolesByRoleTemplateId("roleTemplateId") (or With instead of By, I can't remember which convention we ended up landing on)

**Comment by andrueastman** [comment]
> directoryRoles(roleTemplateId='{roleTemplateId}') => DirectoryRolesByRoleTemplateId("roleTemplateId") (or With instead of By, I can't remember which convention we ended up landing on)

It would be `DirectoryRolesWithRoleTemplateId`. 

As @baywet highlights, Kiota should be able to handle both paths without issue and having them in the openApi reference would unlock the alternate paths in the SDK request builders.

**Review by baywet — APPROVED** [review]

**Pull request merged**
