### PR TITLE
Adds ReadRestrictions and InsertRestrictions for places EntitySet

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/269

This PR:
- Removes readability and insertability for `places` entity set.
- Updates the output test file accordingly.

### CODE REVIEW

**Comment by baywet** [comment]
I'm wondering how the conversion code will react to this change?
Since we won't be inserting the segment for /places anymore, wouldn't that mean the odata cast subsegments won't get inserted as well?

**Comment by irvinesunday** [comment]
> I'm wondering how the conversion code will react to this change? Since we won't be inserting the segment for /places anymore, wouldn't that mean the odata cast subsegments won't get inserted as well?

Let me validate this

**Comment by irvinesunday** [comment]
> I'm wondering how the conversion code will react to this change? Since we won't be inserting the segment for /places anymore, wouldn't that mean the odata cast subsegments won't get inserted as well?

We can still generate the following paths:
- /places/{place-id}
- /places/{place-id}/microsoft.graph.room
- /places/$count
- /places/microsoft.graph.room
- /places/microsoft.graph.room/$count

**Review by baywet — APPROVED** [review]
Thanks for taking the time to check

**Review by baywet — APPROVED** [review]

**Review by baywet — APPROVED** [review]

**Pull request merged**
