### PR TITLE
Schema sync 2022-12-16 from 1.2.169.0

### PR DESCRIPTION
**Pull request by marabooy**
Schema sync 2022-12-16 from 1.2.169.0

### CODE REVIEW

**Comment by darrelmiller** [comment]
@irvinesunday   Can you investigate why this is failing?

**Comment by irvinesunday** [comment]
@marabooy the v1.0-Prod file doesn't have the `Org.OData.Capabilities.V1.ReadRestrictions`. Could you check on this?

**Comment by irvinesunday** [comment]
> @irvinesunday Can you investigate why this is failing?

There was an issue with the metadata parser validation script: https://github.com/microsoftgraph/msgraph-metadata/blob/master/scripts/run-metadata-validation.ps1 which has since been resolved by this PR: https://github.com/microsoftgraph/msgraph-metadata/pull/257

**Comment by marabooy** [comment]
Closing this and manually triggering a refresh. Also looking into the sync issue so this is more frequent.

**Comment by marabooy** [comment]
@irvinesunday the new sync seems to work could you check if this has any missing annotations that may exist in $metadata. https://github.com/microsoftgraph/msgraph-metadata/pull/272/files

**Pull request closed without merging**
