### PR TITLE
Fix for operations bound to `directoryObjects/deletedItems`

### LINKED ISSUE #449: DirectoryObject bound operations not generated on `/directory/deletedItems`
This is a side effect of https://github.com/microsoftgraph/msgraph-metadata/pull/442

The actions/functions bound to the `/directory/deletedItems` are no longer generated. Some of these may not need to be restored. 

Operations include
- delta
- getByIds
- getAvailableExtensionProperties
- validateProperties
- checkMemberGroups
- checkMemberObjects
- getMemberGroups
- getMemberObjects
- restore

References
- https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=http

### PR DESCRIPTION
**Pull request by andrueastman**
Closes #449 

Adds `Org.OData.Core.V1.ExplicitOperationBinding` and `Org.OData.Core.V1.RequiresExplicitBinding` annotations to functions bound to directory objects type to unlock generation of functions/actions on `/deletedItems` path

Depends on release of https://github.com/microsoft/OpenAPI.NET.OData/pull/430

### CODE REVIEW

**Comment by andrueastman** [comment]
**Validation notes**
This PR ends up dropping functions/actions listed above in the following navigation properties paths that are of the type `directoryObject` paths in the final openApi metadata which looks to be valid given the testing and available documentation leading to some path reduction.

1. `/groups/{group-id}/permissionGrants` - No supporting docs and queries fail on GE. Can only be listed according to the [docs](https://learn.microsoft.com/en-us/graph/api/group-list-permissiongrants?view=graph-rest-1.0&tabs=http). Contains target is true. 
2. `/teams/{group-id}/permissionGrants` - No supporting docs and queries fail on GE. Can only be listed according to the [docs](https://learn.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-1.0&tabs=http). Contains target is true. 
3. `/chats/{group-id}/permissionGrants` - No supporting docs and queries fail on GE. Can only be listed according to the [docs](https://learn.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-1.0&tabs=http). Contains target is true. 
4. `/identityGovernance/entitlementManagement/connectedOrganizations/{id}/externalSponsors` - No supporting docs and queries fail on GE. Can only [Add](https://learn.microsoft.com/en-us/graph/api/connectedorganization-post-externalsponsors?view=graph-rest-1.0&tabs=http), [list ](https://learn.microsoft.com/en-us/graph/api/connectedorganization-list-externalsponsors?view=graph-rest-1.0&tabs=http)and [delete](https://learn.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&tabs=http). Should probably have contains target as false?. 
5. `/identityGovernance/entitlementManagement/connectedOrganizations/{id}/internalSponsors` - No supporting docs and queries fail on GE. Can only Add, list and delete. Should probably have contains target as false? . Similar to externalSponsors above in 4.
6. `/policies/appManagementPolicies/{id}/appliesTo` - No supporting docs and ContainsTarget is false. Ideally functions/actions should not be bound to references.

**Review by baywet — CHANGES_REQUESTED** [review]
Let's also set the internal and external sponsors to contains target false since
https://learn.microsoft.com/en-us/graph/api/connectedorganization-post-internalsponsors?view=graph-rest-1.0&tabs=http uses a $ref to add a sponsor.

**Comment by andrueastman** [comment]
> Let's also set the internal and external sponsors to contains target false since https://learn.microsoft.com/en-us/graph/api/connectedorganization-post-internalsponsors?view=graph-rest-1.0&tabs=http uses a $ref to add a sponsor.

Agreed. Resolved in latest update

**Review by baywet — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
