### PR TITLE
Schema sync 2023-02-20 from 1.2.243.0

### PR DESCRIPTION
**Pull request by marabooy**
Schema sync 2023-02-20 from 1.2.243.0

### CODE REVIEW

**Comment by irvinesunday** [comment]
@marabooy how about some of the missing restrictions annotations, e.g. ReadRestrictions in v1.0?

**Comment by darrelmiller** [comment]
@marabooy Ping?  What is the status on getting all the annotations into both v1 and beta so we can improve all of our devX experiences.

**Comment by marabooy** [comment]
@darrelmiller we should have these flow in to the system by end of this week during the friday sync. I also noticed the sync job has been failing.

**Comment by marabooy** [comment]
@darrelmiller I have a new sync done which should have all annotations that are present in the schema files. 
I believe the annotations that may have caused the earlier issue may have been unpublished in prod but are available in beta. 

@irvinesunday kindly check the pr here https://github.com/microsoftgraph/msgraph-metadata/pull/312

**Pull request closed without merging**
