### PR TITLE
Removes delta function for the derived type `administrativeUnit`

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/276

This PR:
- Removes the `delta` function of type `Collection(graph.administrativeUnit)`.
- Adds a test to validate this.

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
I think that once we remove it for that type, the next type (alphabetically) will fail too, we probably need to remove it for all types that derive from directory object (either directly or indirectly), what do you think?

**Comment by irvinesunday** [comment]
> I think that once we remove it for that type, the next type (alphabetically) will fail too, we probably need to remove it for all types that derive from directory object (either directly or indirectly), what do you think?

Since the base type probably has several derived types, I think it will be better having the duplicate path generation issue fixed in the conversion lib. Otherwise, it will require identifying all the derived types and applying their fixes.

**Comment by baywet** [comment]
> Since the base type probably has several derived types, I think it will be better having the duplicate path generation issue fixed in the conversion lib. Otherwise, it will require identifying all the derived types and applying their fixes.

Agreed that it'll scale better and ease up the maintenance. The question the generation is now blocked. How soon can we get the fix out to unblock it if we want to skip the XSLT fix?

**Comment by irvinesunday** [comment]
> > Since the base type probably has several derived types, I think it will be better having the duplicate path generation issue fixed in the conversion lib. Otherwise, it will require identifying all the derived types and applying their fixes.
> 
> Agreed that it'll scale better and ease up the maintenance. The question the generation is now blocked. How soon can we get the fix out to unblock it if we want to skip the XSLT fix?

I'll work on it ASAP.

**Comment by baywet** [comment]
Closing since the fix is implemented in the conversion lib now.

**Pull request closed without merging**
