### PR TITLE
Fixes `ContainsTarget` inaccuracies

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/248

This PR:
- Fixes the inaccuracies highlighted by the aforementioned issue above.
- Updates the output test file.

### CODE REVIEW

**Review by baywet — APPROVED** [review]
Thanks for fixing this!

**Comment by baywet** [comment]
actually @irvinesunday we might still be missing the comment that @peombwa left on the issue about the children nav property

**Comment by andrueastman** [comment]
> actually @irvinesunday we might still be missing the comment that @peombwa left on the issue about the children nav property

Any chance we could fix that before the merge?

**Comment by irvinesunday** [comment]
> actually @irvinesunday we might still be missing the comment that @peombwa left on the issue about the children nav property

Thanks for bringing my attention to that. I missed it!

**Review by baywet — APPROVED** [review]

**Review by peombwa — APPROVED** [review]

**Review by andrueastman — APPROVED** [review]

**Pull request merged**
