### PR TITLE
Do not remove namespaces in XSL tranformation

### PR DESCRIPTION
**Pull request by zengin**
- Dropped the transformation that removes namespaces
- Added a script to run XSL transformation from command line
- Updated readme to refer to the new script

[AB#5024](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5024)

### CODE REVIEW

**Comment by zengin** [comment]
@MIchaelMainer, my change in the XSL doesn't explain why there is a diff for the `<EntityContainer>` element. I don't see a rule which removes that. Is it just that the output file was stale?

**Comment by zengin** [comment]
@ddyett Azure Boards bot doesn't seem to be updating the task link for this PR. Do we miss the link between the repo and the board?

**Comment by MIchaelMainer** [comment]
That output file was stale. The EntityContainer should've been there. Your checkin corrects it. 

The transform via script is way better!

**Comment by zengin** [comment]
Not merging this until downstream handling of multiple namespaces are ready in Typewriter.

**Comment by MIchaelMainer** [comment]
@zengin I want your script and I'm impatient so I'm going to add it in another PR.

**Comment by zengin** [comment]
I am closing this pull request.

I will create another one with 2 transforms, one that drops namespaces, another that doesn't. After reaching to a state where we have steady releases, we will go back to a single transform that keeps all the namespaces.

**Pull request closed without merging**
