### PR TITLE
fix: derivedTypedFor mobileApps

### PR DESCRIPTION
**Pull request by svrooij**
Fixed: #420

### CODE REVIEW

**Review by baywet — APPROVED** [review]
Thanks for the contribution! @irvinesunday for final review and merge

**Comment by svrooij** [comment]
@baywet yeah why not, here is the PR. I've looked for all the none abstract types that have a BaseType of `mobileApp` or `mobileLobApp` and this is the complete list.

I must say I'm flying pretty blind here, but is seems to transform the beta metadata correctly

**Comment by baywet** [comment]
That sounds about right to me, and I believe the reason why we were missing all those types is because when we added this transformation, they didn't exist. What might be missing are derived types from derived types of mobileApp (if any exist).
And yes, the level of complexity is why we usually don't expect external contributions here.

**Comment by svrooij** [comment]
@baywet or @irvinesunday what needs to happen to move this pr forward? Would really like to see this shortcoming in the docs and sdks fixed.

I seem to not be allowed to extend the Kiota request builders, "everything is done through metadata and code generation", but this part is missing in the metadata.

**Comment by baywet** [comment]
LGTM to me, waiting on @irvinesunday to review and merge

**Review by irvinesunday — APPROVED** [review]
LGTM

**Comment by svrooij** [comment]
The documentation on the mobileContentType still seems incorrect, I'm guessing this process will take some time?

Is there "nightly" documentation available somewhere, maybe only for people with an account in the Microsoft tenant?

https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappcontent-create?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985

**Comment by andrueastman** [comment]
@svrooij What specifically is seems incorrect with the docs? 
Ideally, for documentation issues, you can submit a change/suggestion by clicking the edit button on the page as below. 
image

Alternatively, the docs are open source on you can also create an issue in this repo. (The previous suggestion will also lead to creating a PR(editing a file) on the same repo.) The issue/PR should be assigned to the relevant API owner writing the doc topic.

https://github.com/microsoftgraph/microsoft-graph-docs-contrib

**Comment by svrooij** [comment]
@andrueastman I'm facing a brick wall here....

Initial issue: I want to upload win32LobApps with the graph sdk for dotnet. I describe my process [here](https://svrooij.io/2023/08/31/publish-apps-to-intune/)

That means, creating the mobileAppContent, creating the mobileAppContentFile and eventually committing the file. All of which described in my post, is not available in the sdk.

Through using the portal I figured out that I need to change the type in the url.

I tried extending the request builders with extension methods, but they are not extendable [by design](https://github.com/microsoft/kiota-abstractions-dotnet/issues/113), which is a bummer...

Eventually @baywet pointed me to the metadata.... https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2073

I have no clue how to get these endpoints in the graph sdk, please help!

**Comment by svrooij** [comment]
@andrueastman to be more precise, I needed these extensions for my app (and doing it this way defeats the purpose of using the sdk in my opinion.) Can you help out to get these in the SDK/documentation? Or maybe @irvinesunday ?

https://github.com/svrooij/WingetIntune/blob/30b5f76fbaa043de94be29c4c05b692b19540b0e/src/WingetIntune/Graph/GraphServiceClientExtensions.cs

and 

https://github.com/svrooij/WingetIntune/blob/30b5f76fbaa043de94be29c4c05b692b19540b0e/src/WingetIntune/Graph/MobileAppsRequestBuilderExtensions.cs

**Comment by andrueastman** [comment]
Thanks for clarifying @svrooij. 

I believe the conversion settings that generate the openApi description may not expand paths further for navigation properties of a derived type once a odata cast paths is encountered.  

Any chance you can create a separate issue for the `/contentVersions` path and then assign it to @irvinesunday or me so this may be investigated/followed up further?

**Pull request merged**
