### PR TITLE
Fixes response types for properties in complex type `appliedConditionalAccessPolicy`

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/263

- Replaces single-valued with collection-valued return types for complex type `appliedConditionalAccessPolicy` for the properties:
  - conditionsNotSatisfied
  - conditionsSatisfied

### CODE REVIEW

**Comment by irvinesunday** [comment]
> This one is confusing. [the example](https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&tabs=http#response-3) still returns a single value (could it be outdated?) @rkodev have we verified the actual payload on the wire? Should we add a condition to apply that just to beta? Have we tried engaging with the product team?

About using a condition to apply just for beta: I considered it, but I decided against it not for any strong reason but just for brevity of code. The result will be the same whether including the condition or otherwise. This is because these properties are not in `v1.0`.

**Comment by remiphilippe** [comment]
if it helps I can confirm it's an array (from azure portal signin logs, on beta api: `"@odata.context": "https://graph.microsoft.com/beta/$metadata#auditLogs/signIns"`, snippet only to avoid anonymization):
```
"appliedConditionalAccessPolicies": [{
            "id": "649c7fea-db9c-4dca-9abf-20921e7c581f",
            "displayName": "CA004: Require multi-factor authentication for all users",
            "enforcedGrantControls": ["Mfa"],
            "enforcedSessionControls": [],
            "sessionControlsNotSatisfied": [],
            "result": "notApplied",
            "conditionsSatisfied": "application",
            "conditionsNotSatisfied": "users",
            "authenticationStrength": null,
            "includeRulesSatisfied": [{
                "conditionalAccessCondition": "application",
                "ruleSatisfied": "allApps"
            }, {
                "conditionalAccessCondition": "users",
                "ruleSatisfied": "allUsers"
            }],
            "excludeRulesSatisfied": [{
                "conditionalAccessCondition": "users",
                "ruleSatisfied": "userId"
            }]
        }],
```

another one with 2 values in conditions satisfied:
```
"appliedConditionalAccessPolicies": [{
            "id": "649c7fea-db9c-4dca-9abf-20921e7c581f",
            "displayName": "CA004: Require multi-factor authentication for all users",
            "enforcedGrantControls": ["Mfa"],
            "enforcedSessionControls": [],
            "sessionControlsNotSatisfied": [],
            "result": "success",
            "conditionsSatisfied": "application,users",
            "conditionsNotSatisfied": "none",
            "authenticationStrength": null,
            "includeRulesSatisfied": [{
                "conditionalAccessCondition": "application",
                "ruleSatisfied": "allApps"
            }, {
                "conditionalAccessCondition": "users",
                "ruleSatisfied": "allUsers"
            }],
            "excludeRulesSatisfied": []
        }],
```

**Comment by baywet** [comment]
@rkodev @irvinesunday gentle reminder on this one. I'm not sure what's holding it at this point?

**Comment by irvinesunday** [comment]
@remiphilippe thank you for the provided snippet.
@baywet I was waiting for a clarification on the payload, to verify whether we expect a single value or an array. Seems I can go ahead and merge this now.

**Review by baywet — APPROVED** [review]

**Pull request merged**
